# Generated by Django 5.2 on 2025-04-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['orders']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='order',
            new_name='orders',
        ),
    ]
